name: Cypress Tests

on: [push] # Запускать при каждом push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cypress run
        # Используем официальный Cypress GitHub Action
        uses: cypress-io/github-action@v6
        with:
          # Включаем запись в Cypress Cloud
          record: true
          # (Опционально) Запуск тестов в параллельном режиме
          # parallel: true 
        env:
          # Передаем ключ для записи, который мы сохранили в секретах
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # (Опционально) Передаем ID проекта, если его нет в cypress.config.js
          # CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # Сообщаем Cypress, что это CI-среда
          CI: true